### ISSUE TITLE
Expose option for text-transform

### ISSUE THREAD

**Issue by jaycincotta** [schiehll/react-alert#113]
react-alert is a beautiful control, well-designed and a joy to use EXCEPT, the messages display in UPPERCASE.  I found a [Stack Overflow article](https://stackoverflow.com/questions/43383930/react-alert-showing-uppercase) with a hack to customize this behavior, but it seems so odd that for all the flexibility it exposes, that this behavior is so hidden.

Please consider exposing a option to specify the desired text-transform applied to alerts.

**Comment by schiehll** [comment]
Hi @jaycincotta! Since v4 we support custom alert templates, so you actually can style it whatever you want. There's an example in the docs [here](https://github.com/schiehll/react-alert#using-a-custom-alert-template).

We are already in v5, so if you are still in v3, I highly recommend you to update as we don't support v3 anymore.
