### ISSUE TITLE
[Enhancement] Pause timeout when cursor hovering alert

### ISSUE THREAD

**Issue by orditeck** [schiehll/react-alert#144]
Hi, thanks for the nice lib.

It'd be a nice feature if the timeout could be paused when the cursor is hovering the alert.

**Comment by besLisbeth** [comment]
Hi @orditeck. It's easily can be done, just adding the events listeners `onMouseEnter`, `onMouseLeave` to the alert template

**Comment by ShannonLCapper** [comment]
I was wondering if I could get some clarity on what needs to be called in the `onMouseEnter` and `onMouseLeave` handlers in the alert template in order to pause the timeout? As far as I can tell, the only option is to omit the `timeout` option completely and implement a custom one inside the alert template that calls `close` directly. Is that correct?

**Comment by besLisbeth** [comment]
Hi @ShannonLCapper, yes it's totally correct. It may be not the best implementation, but it's the working one. I use such construction in one of my projects.
