### ISSUE TITLE
Question: CSS strange classnames...

### ISSUE THREAD

**Issue by Tzaphkiel** [schiehll/react-alert#23]
Hello,

Thanks for the great and very useful lib.

I've noticed that in the latest version (v2.0.1), I don't see the expected classes (react-alerts) on the DOM element.
I'm wondering if I've done something wrong for that to happen... 
On the demo application, it works properly, in my previous application, it also worked fine and now here I have this:

```html
<div class="css-5wn51h">
  <span>
    <div class="css-1vm9g5e">
      <div class="css-1vuw43k">
        <div class="css-1f1jd2h"></div>
      </div>
      <div class="css-6bx4c3">Fetching node info for internal, 9702069 failed: 404 -&gt; Not Found</div>
      <div class="css-1lf6zld"></div>
    </div>
  </span>
</div>
```

![image](https://cloud.githubusercontent.com/assets/644489/26665912/03b531d0-469d-11e7-9921-a2322da6b719.png)

```javascript
const alertOptions = {
  offset: 10,
  position: 'bottom right',
  theme: 'dark',
  time: 0,
  transition: 'fade'
}
...
<AlertContainer className='Alerts' ref={(a) => global.msg = a} {...alertOptions} />
```

Even the className set on the container element does not seem to appear.
In the react tab of the developer tools in Chrome I correctly see it however.

![image](https://cloud.githubusercontent.com/assets/644489/26665991/882740de-469d-11e7-8f82-55434f3401d7.png)

Any ideas?

**Comment by schiehll** [comment]
Hi @Tzaphkiel ,

The reason why the classes names are like that it's because we are using [glamourous](https://github.com/paypal/glamorous) under the hood. It generates the className for us, so our classes won't mess up with your project's own classes or with any other dependency you may be using.

Also, this lib is not really designed to be that flexible, that's why we have the dark and light themes, the idea was to it be a drop-in-ready-to-use-already-looks-beautiful alert.

But if all you want is to change the style of the message (not the alert itself) you can do so. All you have to do is to pass a react element as the message like this:

`this.msg.success(<div className="your-class">The Message</div>)`

Is that what you trying to do? Or you have other use case?

Oh, and the demo is still using the v1 of the lib, that's why it's using the old classes, sorry if that's confusing, I didn't have the time to change the demo and the appearance would be identical, so I didn't think it would matter.

**Comment by Tzaphkiel** [comment]
Hi @schiehll ,

Thank you for the clarification. I thought indeed that it had to do with the Glamor used.
Btw, I was still using `"react-alert": "1.0.14"` in the previous application...

My idea was to tailor the size of the text in the notification content. I actually wanted a (more) discreet notification that could potentially thus be ignored or not impact too much the user when manipulating the interface, especially when it is an info and not a warning or an error.

Your solution works and is good enough for the moment, but I still find the buttons, etc. a bit big:
![image](https://cloud.githubusercontent.com/assets/644489/26680356/67a2e624-46d9-11e7-8cb2-aeaac03d3c62.png)

If you ever have the time, inclination or are looking for a challenge ;-) perhaps you could consider allowing the addition of an extra class at multiple level to tweak the defaults or some similar solution?

**Comment by schiehll** [comment]
Nice! Glad it did help!

But yeah, that's something that could be really useful for some use cases, I may add it in the future if I have the time.
